<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7ea675db-eff4-488e-9f4f-8eac5d8b2d59</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <SpaRoot>..\webstoreapp.client</SpaRoot>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:28344</SpaProxyServerUrl>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\CRM\Agreements\**" />
    <Compile Remove="Services\CRM\Clients\**" />
    <Compile Remove="Services\CRM\Contractors\**" />
    <Compile Remove="Services\CRM\Delivers\**" />
    <Compile Remove="Services\CRM\Materials\**" />
    <Compile Remove="Services\CRM\Offices\**" />
    <Compile Remove="Services\CRM\Payments\**" />
    <Compile Remove="Services\CRM\Products\**" />
    <Compile Remove="Services\CRM\Sources\**" />
    <Compile Remove="Services\CRM\Tasks\**" />
    <Compile Remove="Services\CRM\Transfrers\**" />
    <Compile Remove="Services\CRM\Users\**" />
    <Compile Remove="Services\NovaPoshta\**" />
    <Content Remove="Services\CRM\Agreements\**" />
    <Content Remove="Services\CRM\Clients\**" />
    <Content Remove="Services\CRM\Contractors\**" />
    <Content Remove="Services\CRM\Delivers\**" />
    <Content Remove="Services\CRM\Materials\**" />
    <Content Remove="Services\CRM\Offices\**" />
    <Content Remove="Services\CRM\Payments\**" />
    <Content Remove="Services\CRM\Products\**" />
    <Content Remove="Services\CRM\Sources\**" />
    <Content Remove="Services\CRM\Tasks\**" />
    <Content Remove="Services\CRM\Transfrers\**" />
    <Content Remove="Services\CRM\Users\**" />
    <Content Remove="Services\NovaPoshta\**" />
    <EmbeddedResource Remove="Services\CRM\Agreements\**" />
    <EmbeddedResource Remove="Services\CRM\Clients\**" />
    <EmbeddedResource Remove="Services\CRM\Contractors\**" />
    <EmbeddedResource Remove="Services\CRM\Delivers\**" />
    <EmbeddedResource Remove="Services\CRM\Materials\**" />
    <EmbeddedResource Remove="Services\CRM\Offices\**" />
    <EmbeddedResource Remove="Services\CRM\Payments\**" />
    <EmbeddedResource Remove="Services\CRM\Products\**" />
    <EmbeddedResource Remove="Services\CRM\Sources\**" />
    <EmbeddedResource Remove="Services\CRM\Tasks\**" />
    <EmbeddedResource Remove="Services\CRM\Transfrers\**" />
    <EmbeddedResource Remove="Services\CRM\Users\**" />
    <EmbeddedResource Remove="Services\NovaPoshta\**" />
    <None Remove="Services\CRM\Agreements\**" />
    <None Remove="Services\CRM\Clients\**" />
    <None Remove="Services\CRM\Contractors\**" />
    <None Remove="Services\CRM\Delivers\**" />
    <None Remove="Services\CRM\Materials\**" />
    <None Remove="Services\CRM\Offices\**" />
    <None Remove="Services\CRM\Payments\**" />
    <None Remove="Services\CRM\Products\**" />
    <None Remove="Services\CRM\Sources\**" />
    <None Remove="Services\CRM\Tasks\**" />
    <None Remove="Services\CRM\Transfrers\**" />
    <None Remove="Services\CRM\Users\**" />
    <None Remove="Services\NovaPoshta\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MassTransit" Version="9.2.0-develop.147" />
    <PackageReference Include="MassTransit.AspNetCore" Version="9.2.0-develop.147" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0-develop.147" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>10.*-*</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Azure.StackExchangeRedis" Version="3.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.6.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
	  
<PackageReference Include="Npgsql" Version="10.0.1" />
	  
<PackageReference Include="Polly" Version="8.7.0" />
	  
<PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
	  
<PackageReference Include="Refit" Version="11.2.0" />
	  
<PackageReference Include="Refit.HttpClientFactory" Version="11.2.0" />
	  
<PackageReference Include="Seq.Extensions.Logging" Version="9.0.0" />
	  
<PackageReference Include="Serilog" Version="4.3.1" />
	  
<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\DAL\DAL.csproj" />
    <ProjectReference Include="..\webstoreapp.client\webstoreprototype.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

</Project>
